package telas;

import DAO.grupoDAO;
import DTO.UsuarioDTO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cassi
 */
public class AdminGrupo extends javax.swing.JFrame {

    /**
     * Creates new form admingrupo
     */
    public AdminGrupo(int idGrupo) {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableMembros.getModel();
        
        readJTableMembros(idGrupo);
    }
    
    private void readJTableMembros(int idGrupo){
        DefaultTableModel modelo = (DefaultTableModel) jTableMembros.getModel();
        modelo.setNumRows(0);
        grupoDAO gdao = new grupoDAO();
        for(UsuarioDTO m: gdao.PegarMembros(idGrupo)){
            if (m.getNota()== 0.0) {
                modelo.addRow(new Object[]{
                m.getUsername(),
                "NA"
                });                
            } else{
            modelo.addRow(new Object[]{
                m.getUsername(),
                m.getNota()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonApagarGrupo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDescricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextContato = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMembros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextTag = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        txtNomeGrupo = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelCriador = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 600));
        getContentPane().setLayout(null);

        jButtonApagarGrupo.setText("Apagar Grupo");
        jButtonApagarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagarGrupo);
        jButtonApagarGrupo.setBounds(270, 490, 110, 40);

        jTextDescricao.setEditable(false);
        jTextDescricao.setColumns(20);
        jTextDescricao.setRows(5);
        jScrollPane2.setViewportView(jTextDescricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 230, 300, 110);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextContato.setEditable(false);
        jTextContato.setColumns(20);
        jTextContato.setRows(5);
        jTextContato.setText("\n");
        jScrollPane3.setViewportView(jTextContato);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(60, 380, 300, 60);

        jLabel1.setText("DESCRIÇÃO DO GRUPO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 200, 300, 30);

        jLabel2.setText("CONTATO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 350, 300, 30);

        jTableMembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Membros", "Nota Média"
            }
        ));
        jScrollPane1.setViewportView(jTableMembros);
        if (jTableMembros.getColumnModel().getColumnCount() > 0) {
            jTableMembros.getColumnModel().getColumn(0).setResizable(false);
            jTableMembros.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 90, 180, 380);

        jLabel3.setText("TAG");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 300, 30);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextTag.setEditable(false);
        jTextTag.setColumns(20);
        jTextTag.setRows(5);
        jScrollPane4.setViewportView(jTextTag);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(60, 150, 300, 30);

        jButton5.setText("Excluir Membro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(150, 490, 114, 40);

        txtNomeGrupo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNomeGrupo.setText("PLACEHOLDER");
        txtNomeGrupo.setToolTipText("");
        getContentPane().add(txtNomeGrupo);
        txtNomeGrupo.setBounds(60, 20, 510, 80);

        jButton6.setText("Voltar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(60, 490, 70, 40);

        jLabel6.setText("Criado por:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 60, 70, 30);

        jLabelCriador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCriador.setText("nomeAqui");
        getContentPane().add(jLabelCriador);
        jLabelCriador.setBounds(470, 60, 140, 30);

        jLabel7.setText("Grupod ID:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 70, 70, 30);

        jLabelId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelId.setText("IDAqui");
        getContentPane().add(jLabelId);
        jLabelId.setBounds(130, 70, 140, 30);

        jLabel5.setText("<html><i> Selecione um membro na tabela para avalia-lo.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 450, 140, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApagarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarGrupoActionPerformed
        // TODO add your handling code here:
        Object[] options = { "Cancelar", "Confirmar" };
        int escolha = (JOptionPane.showOptionDialog(null, "Tem certeza que deseja APAGAR esse grupo? A exclusão é permanente.", "Apagar Grupo?",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]));
        System.out.println(escolha);
        if (escolha == 0) { //Cancelar
            //dispose();                   
        }else{ //Confirmar
            ChamarApagarGrupo(); }
    }//GEN-LAST:event_jButtonApagarGrupoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        telas.Inicio telaInicio = new Inicio();
                            telaInicio.setVisible(true);
                            dispose(); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonApagarGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabelCriador;
    public javax.swing.JLabel jLabelId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableMembros;
    public javax.swing.JTextArea jTextContato;
    public javax.swing.JTextArea jTextDescricao;
    public javax.swing.JTextArea jTextTag;
    public javax.swing.JLabel txtNomeGrupo;
    // End of variables declaration//GEN-END:variables
    public void ChamarApagarGrupo(){
        String grupoId = jLabelId.getText();
        grupoDAO grupo = new grupoDAO();
        grupo.ApagarGrupo(grupoId);
        MeusGrupos telaMeusGrupos = new MeusGrupos();
                            telaMeusGrupos.setVisible(true);
                            dispose();  
    }
}

