/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.grupoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alves
 */
public class CriarGrupo extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public CriarGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtContato = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCriarGrupo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtNomeGrupo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTag = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtNomeGrupo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 600));
        getContentPane().setLayout(null);

        jButton3.setText("VOLTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 500, 130, 50);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 270, 430, 110);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtContato.setColumns(20);
        txtContato.setRows(5);
        jScrollPane3.setViewportView(txtContato);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(60, 420, 430, 60);

        jLabel1.setText("INSIRA A DESCRIÇÃO DO GRUPO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 240, 430, 30);

        jLabel2.setText("MEIO DE CONTATO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 390, 430, 30);

        btnCriarGrupo.setText("CRIAR GRUPO");
        btnCriarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriarGrupo);
        btnCriarGrupo.setBounds(350, 500, 140, 50);

        jLabel4.setText("TITULO DO GRUPO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 80, 430, 30);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtNomeGrupo.setColumns(20);
        txtNomeGrupo.setRows(5);
        jScrollPane5.setViewportView(txtNomeGrupo);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(60, 110, 430, 20);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtTag.setColumns(20);
        txtTag.setRows(5);
        jScrollPane4.setViewportView(txtTag);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(60, 180, 430, 30);

        jLabel3.setText("DEFINA A TAG DO SEU GRUPO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 150, 430, 30);

        txtNomeGrupo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNomeGrupo2.setText("CRIAÇÃO DE GRUPO");
        txtNomeGrupo2.setToolTipText("");
        getContentPane().add(txtNomeGrupo2);
        txtNomeGrupo2.setBounds(60, 0, 510, 80);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        telas.Inicio telaInicio = new Inicio();
                            telaInicio.setVisible(true);
                            dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCriarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarGrupoActionPerformed
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_btnCriarGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarGrupo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txtContato;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextArea txtNomeGrupo;
    private javax.swing.JLabel txtNomeGrupo2;
    private javax.swing.JTextArea txtTag;
    // End of variables declaration//GEN-END:variables

    //metodos
    private void Validar() {

        if (txtNomeGrupo.getText().isEmpty() || txtTag.getText().isEmpty() || txtDescricao.getText().isEmpty() || txtContato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos de cadastro corretamente!");
        } else {
            System.out.println("Informações de Grupo preenchidas corretamente.");
            grupoDAO a = new grupoDAO();
            a.criarGrupo(txtNomeGrupo.getText(), txtTag.getText(), txtDescricao.getText(), txtContato.getText());
            telas.Inicio telaInicio = new Inicio();
                            telaInicio.setVisible(true);
                            dispose();
        }
    } 
     
}
