/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.usuarioDAO;
import telas.Login;
import javax.swing.JOptionPane;

/**
 *
 * @author Alves
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMudarSenha = new javax.swing.JButton();
        btnApagarConta = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTelefone = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNome = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtUser = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuarios-alt (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 410, 24, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/definicoes (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 510, 24, 24);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/casa.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 460, 24, 24);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setDoubleBuffered(false);
        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        btnMudarSenha.setText("Mudar sua Senha");
        btnMudarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMudarSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMudarSenha);
        btnMudarSenha.setBounds(250, 400, 140, 40);

        btnApagarConta.setBackground(new java.awt.Color(255, 102, 102));
        btnApagarConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnApagarConta.setForeground(new java.awt.Color(51, 51, 51));
        btnApagarConta.setText("Apagar Conta");
        btnApagarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarContaActionPerformed(evt);
            }
        });
        jPanel1.add(btnApagarConta);
        btnApagarConta.setBounds(90, 460, 460, 40);

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(90, 400, 140, 40);

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 102));
        jButtonSalvar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSalvar.setText("Salvar Alterações");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(76, 22));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(76, 22));
        jButtonSalvar.setPreferredSize(new java.awt.Dimension(76, 22));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(410, 400, 140, 40);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(txtTelefone);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(90, 330, 460, 30);

        jLabel2.setText("Digite seu TELEFONE:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 310, 410, 16);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportView(txtNome);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(90, 270, 460, 30);

        jLabel10.setText("Digite seu NOME:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 250, 410, 16);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportView(txtUser);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(90, 210, 460, 30);

        jLabel4.setText("Digite seu USER:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 190, 410, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("EDIÇÃO DE PERFIL");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 110, 410, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, -20, 650, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        Validar();
        telas.Inicio telaInicio = new Inicio();
                            telaInicio.setVisible(true);
                            dispose();
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        telas.Inicio telaInicio = new Inicio();
                            telaInicio.setVisible(true);
                            dispose();                                
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnMudarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMudarSenhaActionPerformed
        // TODO add your handling code here:
        String senhaNova = JOptionPane.showInputDialog("Insira sua nova senha");
        ValidarSenha(senhaNova);
    }//GEN-LAST:event_btnMudarSenhaActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        telas.MeusGrupos telaGruposUsuario = new MeusGrupos();
                            telaGruposUsuario.setVisible(true);
                            dispose(); 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        telas.Inicio telaInicio = new Inicio();
                            telaInicio.setVisible(true);
                            dispose(); 
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnApagarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarContaActionPerformed
        // TODO add your handling code here:      
        Object[] options = { "Cancelar", "Confirmar" };
        int escolha = (JOptionPane.showOptionDialog(null, "Tem certeza que deseja apagar sua conta?", "Apagar conta",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]));
        System.out.println(escolha);
        if (escolha == 0) { //Cancelar
            telas.Perfil telaPerfil = new Perfil();
                telaPerfil.setVisible(true);
                dispose();                   
        }else //Confirmar
            ChamarApagar(); 
            dispose();
     
    
    }//GEN-LAST:event_btnApagarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarConta;
    private javax.swing.JButton btnMudarSenha;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane txtNome;
    private javax.swing.JTextPane txtTelefone;
    private javax.swing.JTextPane txtUser;
    // End of variables declaration//GEN-END:variables

     private void Validar() {
        if (txtUser.getText().isEmpty() &&  txtNome.getText().isEmpty() &&  txtTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha ao menos um dos campos para atualizar seu cadastro.");
        } else if (!txtUser.getText().isEmpty() && txtNome.getText().isEmpty() && txtTelefone.getText().isEmpty()) {
            System.out.println("NINCKNAME");     
        } else if (txtUser.getText().isEmpty() && !txtNome.getText().isEmpty() && txtTelefone.getText().isEmpty()) {
            System.out.println("NOME");    
        } else if (txtUser.getText().isEmpty() && txtNome.getText().isEmpty() && !txtTelefone.getText().isEmpty()) {
            System.out.println("TELEFONE");
        } else if (!txtUser.getText().isEmpty() && txtNome.getText().isEmpty() && txtTelefone.getText().isEmpty()) {
            System.out.println("NINCKNAME E NOME");
        } else if (!txtUser.getText().isEmpty() && txtNome.getText().isEmpty() && !txtTelefone.getText().isEmpty()) {
            System.out.println("NINCKNAME E TELEFONE");
        } else if (txtUser.getText().isEmpty() && !txtNome.getText().isEmpty() && !txtTelefone.getText().isEmpty()) {
            System.out.println("NOME E TELEFONE");
        } else {  
            System.out.println("TODOS");
            usuarioDAO user = new usuarioDAO();
            user.atualizar(txtUser.getText(), txtNome.getText(), txtTelefone.getText()); 
        }
     }
     
     private void ValidarSenha(String senha){
          if (!senha.equals("")) { 
            usuarioDAO user = new usuarioDAO();//
            user.AtualizarSenha(senha);}            
        }
          
     private void ChamarApagar(){
         usuarioDAO user = new usuarioDAO();//
            user.Apagar();   
     }
         
}
